PREP(applyDimensions);
PREP(applyHandlers);
PREP(applyInheritableProperty);
PREP(applyInheritableProperties);
PREP(buildControl);
PREP(buildControlsGroup);
PREP(createControlCommon);
PREP(parseColor);
PREP(parseControlProperty);
