name = "A3U Singleplayer Cheat Menu"
author = "goreSplatter"
prefix = "a3uspcm"
mainprefix = "z"

[files]
include = [
    "a3uspcm.paa",
    "LICENSE",
    "mod.cpp"
]

[lints.sqf]
format_args = false
