name = "A3U Singleplayer Cheat Menu"
author = "goreSplatter"
prefix = "a3uspcm"
mainprefix = "z"

[files]
include = [
    "a3uspcm.paa",
    "LICENSE",
    "mod.cpp"
]

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE3
    "3020755032", # Antistasi Ultimate
    "1779063631", # ZEN
]
parameters = [
    "-skipIntro",           # These parameters are passed to the Arma 3 executable
    "-noSplash",            # They do not need to be added to your list
    "-showScriptErrors",    # You can add additional parameters here
    "-debug",
    "-filePatching",
]
