name = "A3U Singleplayer Cheat Menu"
author = "goreSplatter"
prefix = "a3uspcm"
mainprefix = "z"

[files]
include = [
    "a3uspcm.paa",
    "LICENSE",
    "README.md",
    "mod.cpp"
]

[hemtt.launch.default]
dlc = ["ef","rf"]
workshop = [
    "450814997", # CBA_A3
    "463939057", # ACE3
    "3020755032", # Antistasi Ultimate
    "1779063631", # ZEN
    "3499977893", # Advanced Developer Tools
]

[hemtt.launch.malden]
extends = "default"
mission = "a3uspcm.Malden"

[lints.sqf]
# Too generic; does not take into account `isNil` checks, for example
direct_private = false
# Complains about if-elses whose branches would have to be exchanged leading to
# one-line else statements you have to scroll for a bit because of a longer then
if_not_else = false
# Promoted to warning
shadowed = "Warning"
# Too generic; `(isNil "_x") && { _x > 0 }` is considered inefficient...
short_circuit_bool_var = false
# Promoted to warning
unused = "Warning"
